### ISSUE TITLE
pypi version

### ISSUE THREAD

**Issue by belasco** [ptrv/gpx2spatialite#28]
Hi Peter,

Trying to update gpx2spatialite recently I notice that pypi serves version 8.0.0 even though you uploaded 8.0.1

I can show this by doing the following on my archlinux box at home:

$ gpx2spatialite --version
 gpx2spatialite 0.8.0
$ sudo pip install gpx2spatialite --upgrade
Requirement already up-to-date: gpx2spatialite in /usr/lib/python3.5/site-packages
Requirement already up-to-date: gpxpy in /usr/lib/python3.5/site-packages (from gpx2spatialite)

Any ideas?

**Comment by ptrv** [comment]
Hi @belasco 

The reason for not being able to update is probably this commit: 26684d176b6377d5a245e269c058400d7dce943d

It basically tells pypi that the package is only supported in python 2.7. Since the verision was not proparly set before that commit, you could install it with python 3, as we can see from your terminal output. I had the impression that `gpx2spatialite` does not work with python 3 (basically never tested it) and so I restricted it to python 2.7

If you have worked with `gpx2spatialite` with python 3 we need to check if everything works with python 3 and then we can remove the python version restriction. Until then you have to use python 2 to install the package.

**Comment by ptrv** [comment]
@belasco I remember overwriting v0.8.1 on pypi. Maybe that broke the package. I bumped the version to v0.8.2 so now you should be able to upgrade
